app{

    nbPartitions = 100

    baseDbPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\db\\base"
    baseCheckpointPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\checkpoint\\base"

    predictedResultsDbPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\db\\predictedResults"
    predictedResultsCheckpointPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\checkpoint\\predictedResults"

    realResultsDbPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\db\\realResults"
    realResultsCheckpointPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\checkpoint\\realResults"

    colorDbPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\db\\color"
    colorCheckpointPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\checkpoint\\color"

    shapeDbPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\db\\shape"
    shapeCheckpointPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\checkpoint\\shape"
}