app {
  input_path = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\input"
  output_path = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\output"
  nb_files = 20
  batch_duration = 1
  is_loop = false
}