app{

    nbPartitions = 10

    baseDbPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\db\\base"
    baseCheckpointPath = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\checkpoint\\base"
}