app {
  input_path = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\input\\Validation"
  output_path = "C:\\Users\\brook\\IdeaProjects\\Spark_Streaming\\src\\main\\resources\\output"
  nb_files = 15
  batch_duration = 20
  is_loop = true
}